version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: ezra-backend-alt
    restart: unless-stopped
    ports:
      - "5002:5001"  # Changed external port to 5002
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DATABASE_URL=/app/data/ezra.db
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here-change-in-production}
      - JWT_EXPIRES_IN=7d
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3006}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - ezra-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: ezra-frontend-alt
    restart: unless-stopped
    ports:
      - "3006:80"  # Changed external port to 3006
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - ezra-network

networks:
  ezra-network:
    driver: bridge

volumes:
  postgres-data: