version: '3.8'

# Ezra Docker Compose for Dockge (Local Images)
# Build images first with: ./build-for-dockge.sh

services:
  # ================================
  # BACKEND SERVICE
  # ================================
  backend:
    image: ezra-backend:latest
    container_name: ezra-backend
    restart: unless-stopped
    ports:
      - "6001:6001"
    environment:
      # Core Configuration
      NODE_ENV: production
      PORT: 6001
      
      # Authentication (REQUIRED - change these!)
      JWT_SECRET: "your-secret-key-here-change-in-production"
      JWT_EXPIRES_IN: "7d"
      ADMIN_SECRET: "idontknow"
      
      # AI Integration (REQUIRED for AI features)
      ANTHROPIC_API_KEY: "your-anthropic-api-key-here"
      
      # Database Configuration
      DATABASE_URL: "/app/data/ezra.db"
      
      # Frontend URL for CORS
      FRONTEND_URL: "http://localhost:3005"
      
      # API Configuration
      API_RATE_LIMIT_WINDOW_MS: "900000"
      API_RATE_LIMIT_MAX: "100"
    volumes:
      - ezra-data:/app/data
      - ezra-uploads:/app/uploads
      - ezra-logs:/app/logs
    networks:
      - ezra-network

  # ================================
  # FRONTEND SERVICE
  # ================================
  frontend:
    image: ezra-frontend:latest
    container_name: ezra-frontend
    restart: unless-stopped
    ports:
      - "3005:80"
    environment:
      VITE_API_URL: "/api"
    depends_on:
      - backend
    networks:
      - ezra-network

networks:
  ezra-network:
    driver: bridge

volumes:
  ezra-data:
    driver: local
  ezra-uploads:
    driver: local
  ezra-logs:
    driver: local