name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        
  size-check:
    name: Check PR Size
    runs-on: ubuntu-latest
    steps:
    - name: Check PR size
      uses: CodelyTV/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        xs_max_size: 10
        s_label: 'size/s'
        s_max_size: 100
        m_label: 'size/m'
        m_max_size: 500
        l_label: 'size/l'
        l_max_size: 1000
        xl_label: 'size/xl'
        
  lint-pr:
    name: Lint PR Title
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        requireScope: false
        subjectPattern: ^[A-Z].+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          starts with an uppercase letter.
          
  test-coverage:
    name: Test Coverage Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: |
        npm run test:frontend -- --coverage --watchAll=false
        cd backend && npm test -- --coverage --watchAll=false
      env:
        NODE_ENV: test
        JWT_SECRET: test-secret-key
        DATABASE_URL: data/test.db
        
    - name: Coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        threshold: 60